language: node_js
node_js:
- 8.9.4
script:
- npm run lint
- npm run build
sudo: false
cache:
  directories:
  - npm_modules
  - pxt_modules
before_deploy:
- sudo pip install --upgrade awscli && aws --version
deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh alpha
    on:
      repo: rovercode/pxt-rovercode
      branch: alpha
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh beta
    on:
      repo: rovercode/pxt-rovercode
      branch: beta
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh prod
    on:
      repo: rovercode/pxt-rovercode
      branch: master
