language: node_js
node_js:
- 8.9.4
script:
- npm install -g pxt
- pxt target microbit
- pxt install
- pxt build
- mv built/binary.hex built/rovercode.hex
sudo: false
cache:
  directories:
  - npm_modules
  - pxt_modules
deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: AKIA3SJYAB3IVB4RTHPU
    secret_access_key:
      secure: TBSGNH8AM618VwCjEnWesRBFuXVtTMJC8BMyOlIIPBPLpqiJJyVZZmrg/7I/BZ8BJJ108T05fggqPmyJA8O4yZWPhPF1VGQkYBPCt/1JjeP/clt/0DJFrJ2NxwHphYBoW/+0tytAG43wlQPqnwvoJarWj6KUmPoJIJihf0kvMq0atLgjiroAZsillmCt2LzWmiwX6uzrqrS3BDV4BOxLmNHAgurzGsUv2f8KYRlZ63CZkPq0FS2dzQnuh+gleO+2RgZAApoItllqRfNsKZa5Bvqk57uhWwbb9Zpa2xblBZRhqI/4C/HK7siaKYDJ/QdnTMFJIPmO+8ejKfvqHekPU0Q3rP6q5/tSFnEYPGXviluQH5srkoB1poI6FXu4+3a9DBlolhCapHsAZwqlzsWLEE5YMrHHdhGyGYQ0QbHWC8LNcYj0hreuMNI8oQLdiVtVSbeC8Jtt/B8nViV0qOafJryaop4+qcAQYcwi35ZZ3xVEI6vvHrzfRPqNkxeRnIz/4QKIezSX7qoVYegKARbgQUbvbKuWhbExHRMx9f7WuTgaGOOYornrpjDb7sum8XGphLF1IT0JBiIgqrPx42PyJifbZvjO2UVloSFCK42VncOdEwmjcpdBM0mhSCoOs/1Nsa1ZuANBeKD4jC2K7t4mRQOCHivtlVtp7miblxYhVys=
    bucket: rovercode-pxt
    region: us-east-2
    local_dir: built
    upload_dir: prod
    acl: public_read
    on:
      repo: rovercode/pxt-rovercode
      branch: master
  - provider: s3
    skip_cleanup: true
    access_key_id: AKIA3SJYAB3IVB4RTHPU
    secret_access_key:
      secure: TBSGNH8AM618VwCjEnWesRBFuXVtTMJC8BMyOlIIPBPLpqiJJyVZZmrg/7I/BZ8BJJ108T05fggqPmyJA8O4yZWPhPF1VGQkYBPCt/1JjeP/clt/0DJFrJ2NxwHphYBoW/+0tytAG43wlQPqnwvoJarWj6KUmPoJIJihf0kvMq0atLgjiroAZsillmCt2LzWmiwX6uzrqrS3BDV4BOxLmNHAgurzGsUv2f8KYRlZ63CZkPq0FS2dzQnuh+gleO+2RgZAApoItllqRfNsKZa5Bvqk57uhWwbb9Zpa2xblBZRhqI/4C/HK7siaKYDJ/QdnTMFJIPmO+8ejKfvqHekPU0Q3rP6q5/tSFnEYPGXviluQH5srkoB1poI6FXu4+3a9DBlolhCapHsAZwqlzsWLEE5YMrHHdhGyGYQ0QbHWC8LNcYj0hreuMNI8oQLdiVtVSbeC8Jtt/B8nViV0qOafJryaop4+qcAQYcwi35ZZ3xVEI6vvHrzfRPqNkxeRnIz/4QKIezSX7qoVYegKARbgQUbvbKuWhbExHRMx9f7WuTgaGOOYornrpjDb7sum8XGphLF1IT0JBiIgqrPx42PyJifbZvjO2UVloSFCK42VncOdEwmjcpdBM0mhSCoOs/1Nsa1ZuANBeKD4jC2K7t4mRQOCHivtlVtp7miblxYhVys=
    bucket: rovercode-pxt
    region: us-east-2
    local_dir: built
    upload_dir: beta
    acl: public_read
    on:
      repo: rovercode/pxt-rovercode
      branch: beta
  - provider: s3
    skip_cleanup: true
    access_key_id: AKIA3SJYAB3IVB4RTHPU
    secret_access_key:
      secure: TBSGNH8AM618VwCjEnWesRBFuXVtTMJC8BMyOlIIPBPLpqiJJyVZZmrg/7I/BZ8BJJ108T05fggqPmyJA8O4yZWPhPF1VGQkYBPCt/1JjeP/clt/0DJFrJ2NxwHphYBoW/+0tytAG43wlQPqnwvoJarWj6KUmPoJIJihf0kvMq0atLgjiroAZsillmCt2LzWmiwX6uzrqrS3BDV4BOxLmNHAgurzGsUv2f8KYRlZ63CZkPq0FS2dzQnuh+gleO+2RgZAApoItllqRfNsKZa5Bvqk57uhWwbb9Zpa2xblBZRhqI/4C/HK7siaKYDJ/QdnTMFJIPmO+8ejKfvqHekPU0Q3rP6q5/tSFnEYPGXviluQH5srkoB1poI6FXu4+3a9DBlolhCapHsAZwqlzsWLEE5YMrHHdhGyGYQ0QbHWC8LNcYj0hreuMNI8oQLdiVtVSbeC8Jtt/B8nViV0qOafJryaop4+qcAQYcwi35ZZ3xVEI6vvHrzfRPqNkxeRnIz/4QKIezSX7qoVYegKARbgQUbvbKuWhbExHRMx9f7WuTgaGOOYornrpjDb7sum8XGphLF1IT0JBiIgqrPx42PyJifbZvjO2UVloSFCK42VncOdEwmjcpdBM0mhSCoOs/1Nsa1ZuANBeKD4jC2K7t4mRQOCHivtlVtp7miblxYhVys=
    bucket: rovercode-pxt
    region: us-east-2
    local_dir: built
    upload_dir: alpha
    acl: public_read
    on:
      repo: rovercode/pxt-rovercode
      branch: alpha
