language: node_js
node_js:
- 8.9.4
script:
- npm run lint
- npm run build
sudo: false
cache:
  directories:
  - npm_modules
  - pxt_modules
deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: $AWS_KEY_NAME
    secret_access_key: $AWS_KEY_SECRET
    bucket: rovercode-pxt
    region: us-east-2
    local_dir: built
    upload_dir: prod
    acl: public_read
    on:
      repo: rovercode/pxt-rovercode
      branch: master
  - provider: s3
    skip_cleanup: true
    access_key_id: $AWS_KEY_NAME
    secret_access_key: $AWS_KEY_SECRET
    bucket: rovercode-pxt
    region: us-east-2
    local_dir: built
    upload_dir: beta
    acl: public_read
    on:
      repo: rovercode/pxt-rovercode
      branch: beta
  - provider: s3
    skip_cleanup: true
    access_key_id: $AWS_KEY_NAME
    secret_access_key: $AWS_KEY_SECRET
    bucket: rovercode-pxt
    region: us-east-2
    local_dir: built
    upload_dir: alpha
    acl: public_read
    on:
      repo: rovercode/pxt-rovercode
      branch: alpha
